version: 2
jobs:
  build:
    working_directory: ~/myapp
    docker:
      - image: circleci/ruby:2.7.4
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: myapp
          POSTGRES_DB: myapp_test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run:
          name: Setup database
          command: |
            bundle exec rails db:create db:schema:load
      - run:
          name: Run tests
          command: |
            bundle exec rspec

