# パイプラインのバージョンを指定
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:3.1.3-node-browsers
        working_directory: ~/mihasi25/src
        environment:
          DATABASE_URL: postgres://user:password@localhost/myapp_test
          RAILS_ENV: test
    steps:
      - checkout
        path: ~/mihasi25
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y postgresql-client
            bundle check --path=vendor/bundle || bundle install --jobs=4 --retry=3 --path=vendor/bundle
      - run:
          name: Configure database
          command: |
            bundle exec rails db:create RAILS_ENV=test
            bundle exec rails db:schema:load RAILS_ENV=test
      - run:
          name: Run tests
          command: |
            bundle exec rspec
